version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"
      - run: python -m pip install -r requirements.txt
      - run: pytest -vvv --cov code
      - codecov/upload

  build_39:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"

  test_39:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"
      - run: python -m pip install -r requirements.txt
      - run: pytest -vvv --cov code
      - codecov/upload

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build

  build_test_39:
    jobs:
      - build_39
      - test_39:
          requires:
            - build_39
