version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"

 test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.executable)"
      - run: pytest test/test_main.py

workflows:
  just_build:
    jobs:
      - build

  build_test:
    jobs:
      - build
      - test:
        requires:
          - build